version: '3'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
  express-test:
    build: .
    container_name: express-test
    environment:
      - .env
    depends_on:
      - mongodb
    ports:
      - "3000:3000"